apiVersion: v1
description: Redis-Cluster Helm chart for Kubernetes
name: redis-cluster
version: 0.0.0
dependencies:
- name: redis-operator
  version: "0.0.0"
  repository: "file://../redis-operator"
